import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center h-screen">
        <h1 className="underline text-4xl">
          This is Clean NextJS and TailwindCSS Template
        </h1>
      </main>
    </div>
  );
}
