import Head from "next/head";
import { Login, Profile } from "../components";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isAuthenticated } = useMoralis();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center h-screen">
        {isAuthenticated ? <Profile /> : <Login />}
      </main>
    </div>
  );
}
